[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.10.0",
    "conan",
    "cmake>=3.12"
]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "numpy>=1.2",
    "matplotlib>=3.4",
    "pybind11"
]
