name: rythm_forge_ci

on:
  push:
  pull_request:
    branches:
      - "main"
      - "ci"
    types: [opened]


jobs:
  linting:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup workspace
        run: |
          sudo apt update
          sudo apt install python3.10
          sudo apt-get install cppcheck
          pip3 install ruff
      - uses: actions/checkout@v3
      - name: Cpp linting
        run: |
          cppcheck --enable=all --std=c++20 --suppressions-list=config/cpp_check_suppress.cppcheck  src/src/ src/modules/
      - name: Python linting
        run: |
          ruff check rythm_forge/

  ubuntu_build:
      runs-on: ubuntu-22.04
      needs: linting
      steps:
        - name: Setup workspace
          run: |
            sudo apt update
            sudo apt install python3.10
            pip3 install pybind11[global]
            pip3 install pytest
        - uses: actions/checkout@v3
        - name: Build
          run: |
            mkdir -p build
            cd build
            cmake -DCMAKE_PREFIX_PATH=$(python3 -m site --user-site) ..
            cmake --build . --target rythm_forge_cpp_unit_tests

        - name: Run Cpp tests
          run: |
            cd build/src/tests/
            ctest

        - name: Install RythmForge python package
          run: |
            pip3 install .
        - name: Run Python tests
          run: |
            pytest tests/

  windows_build:
      runs-on: windows-latest
      needs: linting
      steps:
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - name: Setup workspace
          run: |
            python3 --version
            pip3 install pybind11[global]
            pip3 install pytest
        - uses: actions/checkout@v3
        - name: Build
          run: |
            mkdir build
            cd build
            cmake ..
            cmake --build . --target rythm_forge_cpp_unit_tests

        - name: Run Cpp tests
          run: |
            cd build\src\tests\
            ctest

        - name: Install RythmForge python package
          run: |
            pip3 install .
        - name: Run Python tests
          run: |
            pytest tests/

        





